apiVersion: v1 
kind: Service 
metadata: 
  name: zabbix-server 
  namespace: default 
  labels: 
    name: zabbix-server
spec:
  type: NodePort
  ports: 
    - port: 10051
  selector: 
    name: zabbix-server 
