apiVersion: v1 
kind: Service 
metadata: 
  name: zabbix-web 
  namespace: default 
  labels: 
    name: zabbix-web
spec:
  type: NodePort
  ports: 
    - port: 80
  selector: 
    name: zabbix-web 
